- hosts: localhost
  connection: local
  tasks:
    - name: Create Linux VM
      azure_rm_virtualmachine:
        ad_user: "ansibleuser@testazure83gmail.onmicrosoft.com"
        password: "Ansible@123"
        subscription_id: "cefc0075-5612-4b84-bf5e-4e143487b9ed"
        resource_group: test1_group
        name: "{{vm_name}}"
        admin_username: "testuser"
        admin_password: "pass@123"
        vm_size: Standard_B1s
        managed_disk_type: Standard_LRS  
        image:
          publisher: oracle
          offer: oracle-linux
          sku: ol86-lvm
          version: latest
        ssh_password_enabled: yes
        public_ip_allocation_method: Disabled
